# Generated by Django 5.0.1 on 2024-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_animal_age_alter_animal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=100)),
                ('YearPublished', models.IntegerField()),
                ('Type', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
