# Generated by Django 5.0.1 on 2024-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='default_book.jpg', null=True, upload_to=''),
        ),
    ]
