# Generated by Django 5.0.1 on 2024-02-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
